// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var rendered, template;
    console.log("void");
    window._app = {};
    _app.colors = [
      {
        "name": "white",
        "hex": "#FFFFFF"
      }, {
        "name": "grey",
        "hex": "#BEBEBE"
      }, {
        "name": "black",
        "hex": "#000000"
      }, {
        "name": "red",
        "hex": "#FF0000"
      }, {
        "name": "blue",
        "hex": "#0000FF"
      }, {
        "name": "yellow",
        "hex": "#FFFF00"
      }, {
        "name": "green",
        "hex": "#008000"
      }, {
        "name": "purple",
        "hex": "#800080"
      }
    ];
    template = $('body').html();
    rendered = Mustache.render(template, _app);
    return $('body').html(rendered);
  });

}).call(this);
